print("Hello world")
print("Hello world")
print("Hello World! we are creating dev branch")
print("This is a sample Python exercise for Git workflow.")
print("Let's practice some basic Python operations.")
print("this commit from dev branch")